#!/bin/bash

make-problem-dir () {
    DIR_NAME=${1}-${2}
    mkdir -p ${DIR_NAME}
}

copy-template-file () {
    DIR_NAME=${1}-${2}
    TEMPLATE_NAME=templates/${3}
    NEW_FILE_NAME=${4} 

    cp ${TEMPLATE_NAME} ${DIR_NAME}/${NEW_FILE_NAME}
}

copy-template-dir () {
    DIR_NAME=${1}-${2}
    TEMPLATE_NAME=${3}
    NEW_FILE_NAME=${4} 

    cp -r ${TEMPLATE_NAME} ${DIR_NAME}/${NEW_FILE_NAME}
}

file-name () {
    LANG=${3}
    if [ "${LANG}" == "Haskell" ]
    then
        FILE_NAME=${DIR_NAME}
    elif [ "${LANG}" == "Python" ]
    then
        FILE_NAME=${2}_${1}
        FILE_NAME=$(echo ${FILE_NAME} | sed -e 's/-/_/g')
    fi

    echo "${FILE_NAME}"
}
make-file-from-template () {
    LANG=${3}
    EXT=${4}
    DIR_NAME=${1}-${2}
    TEMPLATE_NAME=template.${EXT}
    FILE_NAME=$(file-name ${1} ${2} ${3})

    cat templates/${LANG}/${TEMPLATE_NAME} \
                         | sed -e "s/<PROBLEM NUMBER>/${1}/g" \
                         | sed -e "s/<PROBLEM NAME>/${2}/g" \
                         | sed -e "s/<PROBLEM DIR>/${DIR_NAME}/g" \
                         | sed -e "s/<FILE NAME>/${FILE_NAME}/g" \
                         > ${DIR_NAME}/${FILE_NAME}.${EXT}
}

make-executable () {
    DIR_NAME=${1}-${2}
    FILE_NAME=${3}
    chmod 744 ${DIR_NAME}/${FILE_NAME}
}

rename-go () {
    DIR_NAME=${1}-${2}
    FILE_NAME=$(file-name ${1} ${2} ${3}).bash
    mv ${DIR_NAME}/${FILE_NAME} ${DIR_NAME}/go
}

if [ "${2}" == "" ] || [ "${3}" == "" ]
then
    echo
    echo "    Usage:  next-problem <PROBLEM NUMBER> <PROBLEM NAME> <Haskell|Python>"
    exit 1
fi

if [ "${3}" == "Haskell" ]
then
    cd ~/git/project-euler

    make-problem-dir ${1} ${2}
    make-file-from-template ${1} ${2} ${3} cabal
    make-file-from-template ${1} ${2} ${3} hs

    make-file-from-template ${1} ${2} ${3} bash
    rename-go ${1} ${2}
    make-executable ${1} ${2} go

elif [ "${3}" == "Python" ]
then
    cd ~/git/project-euler

    make-problem-dir ${1} ${2}
    make-file-from-template ${1} ${2} ${3} py

    make-file-from-template ${1} ${2} ${3} bash
    rename-go ${1} ${2}
    make-executable ${1} ${2} go

else
    echo "${3} is an unknown language template.  Please try again."
fi
